#!/usr/bin/env bash

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

# Initialize stack.
fin project start

${PROJECT_ROOT}/bin/init.sh

# Repeat here just to show the site URL when we are done.
fin project start
